### ISSUE TITLE
warning: $levelpad in Logger message format is deprecated, please remove it

### ISSUE THREAD

**Issue by bortzmeyer** [pma/logger_syslog_backend#5]
This warning appears on Elixir 1.14.0 (but not on 1.10.3). It seems it comes from the `@default_format` attribute, which does indeed include a `levelpad`:

```
% mix run something.exs
Compiling 1 file (.ex)
warning: $levelpad in Logger message format is deprecated, please remove it
  (logger 1.14.0) lib/logger/formatter.ex:155: Logger.Formatter.compile_code/1
  (logger 1.14.0) lib/logger/formatter.ex:148: anonymous fn/2 in Logger.Formatter.compile/1
  (elixir 1.14.0) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
  (logger 1.14.0) lib/logger/formatter.ex:146: Logger.Formatter.compile/1
  (logger_syslog_backend 1.0.2) lib/logger_syslog_backend.ex:68: LoggerSyslogBackend.configure/3
  (logger_syslog_backend 1.0.2) lib/logger_syslog_backend.ex:10: LoggerSyslogBackend.init/1
```

**Comment by pma** [comment]
Closed by https://github.com/pma/logger_syslog_backend/pull/6
